### ISSUE TITLE
Incompatibility with Lithium

### ISSUE THREAD

**Issue by Retidurc** [ArkoSammy12/creeper-healing#7]
Hello ! Seems the mod have some kind of incompatibility with lithium.
I am using Lithium 0.12.1 on Minecraft 1.20.4.
I will also post this on the Lithium Tracker, i'm not sure which mod is realy responsible for the bad interaction.

When both are used at the same time, the game crashes at startup with this log : 

```
java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.client.main.Main.main(Main.java:170)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_148: Lithium Class Analysis
	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.hasMethodOverride(ReflectionUtil.java:46)
	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.isBlockStateEntityTouchable(ReflectionUtil.java:64)
	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:116)
	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:113)
	at net.minecraft.class_4970$class_4971.initFlags(class_4970.java:2942)
	at net.minecraft.class_4970$class_4971.handler$bik004$lithium$init(class_4970.java:2931)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:932)
	at net.minecraft.class_2246.<clinit>(class_2246.java:1253)
	... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of xd.arkosammy.creeperhealing.mixin.ExplosionDamageSourceInvoker failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2673)
	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.hasMethodOverride(ReflectionUtil.java:23)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: xd.arkosammy.creeperhealing.mixin.ExplosionDamageSourceInvoker is in a defined mixin package xd.arkosammy.creeperhealing.mixin.* owned by creeper-healing.mixins.json and cannot be referenced directly
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 29 more
```

**Comment by ArkoSammy12** [comment]
Hello. This is most likely an issue on my part. I will get it fixed asap. Thanks for reporting!

**Comment by ArkoSammy12** [comment]
Hello @Retidurc , I have published a new [release](https://modrinth.com/mod/creeper-healing/version/0.1.8.1-1.20.3+) of the mod that fixes this issue. Thank you for reporting. Let me know if you encounter any further problems :D
